Remind.me-master/config/routes.rb
RemindmeV2::Application.routes.draw do
  # Google OAuth
#  mount GoogleAuthentication, :at => '/auth/google'

  devise_for :users

  devise_scope :user do
    get "logout", :to => "devise/sessions#destroy"
  end

  resource :public, :only => :index
  get '/search' => "application#search"


  namespace 'admin' do 
    resources :terapeuts do 
      member do 
        get :remove
      end
    end
  end

  resource :calendar, :only => [:show, :create, :destroy], controller: 'calendars',  as: 'my_calendar' do
    collection do 
      get :events
      get :persons
    end
  end

  resources :calendars, :only => [:show, :create, :destroy] do
    member do 
      get :events 
      post :create
    end
  end

  resource :statistics do
    get '/people/:people(/from/:from(/to/:to))' => "statistics#show"
  end


  resource :dashboard, :only => :show

  resource :exports do 
    get :perform
  end

  resource :settings do 
    collection do 
      get :refresh_google_status
      post :invite_user
      get :remove_user_access
      post :reminders
    end
  end

  resources :patients do 
    collection do 
      get :autocomplete
    end
    member do
      get :activate
      post :activate
      get :session
      get :notes
      get :delete
      get :resend_invitation
    end
  end
  
  match 'smsteknik/webhook' => 'api/v1/sms#receive_sms', :as => :smsteknik, :via => :post

  namespace 'api' do 
    namespace 'v1' do 
      resource :sms, :only => [] do 
        post :status
      end
    end
  end

  root :to => 'public#index'

end

Remind.me-master/app/controllers/settings_controller.rb
#coding:utf-8
class SettingsController < ApplicationController
	before_filter :authenticate_user!
	before_filter :setup_deferred_editing, :only => [:reminders]

	def show
		@users_with_access_to_user = current_user.given_permission_to
	end

	def edit
		@user = current_user
	end

	def update
		respond_to do |format|
			if current_user.update_attributes(params[:user]) 
				flash[:notice] = "Information uppdaterad."
				format.html{ redirect_to settings_path and return }
			else
				flash[:error] = "Något gick tyvärr fel!"
				logger.info current_user.errors.inspect
				format.html{ @user = current_user; render :action => :edit and return }				
			end
		end
	end

	def reminders
		respond_to do |format|
			if @user.set_default_reminders(params[:reminders])
				format.html{ render :partial => 'reminder_list', :locals => {:user => @user} }
			else
				format.html{ render :nothing => true, :status => 500 and return }
			end
		end
	end

	def remove_user_access
		u = User.find(params[:user_id])

		if u.nil?
			redirect_to :action => :show and return
		else 
			if current_user.given_permission_to.delete(u)
				UserMailer.send_removed_access_notification(current_user, u).deliver_now
			end
			redirect_to :action => :show and return
		end		
	end

	def invite_user

		u = User.where(:email => params[:email].strip).first

		if params[:email].blank?
			flash[:error] = "Du måste ange en email."
			redirect_to :action => :show and return
		elsif u.nil? 
			u = Viewer.invite!({:email => params[:email]}, current_user)
			u.update_attribute('type', 'Viewer')
			Permission.create(:user => u, :access_to => current_user)
			flash[:notice] = "Inbjudan skickad"		
		else
			if u == current_user
				flash[:notice] = "Du kan inte lägga till dig själv"
				redirect_to :action => :show and return
			elsif current_user.given_permission_to.include?(u)
				flash[:notice] = "Användaren har redan tillgång till din kalender"
				redirect_to :action => :show and return
			end
			Permission.create(:user => u, :access_to => current_user)
			flash[:notice] = "Användare tillaggd"
			# Här borde vi skicka ett email eller skapa en notification
			UserMailer.send_access_notification(current_user, u).deliver_now
		end
		redirect_to :action => :show and return
	end

	def refresh_google_status
		render :partial => 'google_account' and return
	end

	private

	def setup_deferred_editing
		tentative_user = User.where(["id = ?", params[:patient_id]]).first
		if current_user.has_role?(:terapeut) && current_user.has_permission_for?(tentative_user)
			@user = tentative_user
		else
			@user = current_user
		end
	end
end

Remind.me-master/app/helpers/settings_helper.rb
module SettingsHelper
end

Remind.me-master/app/views/settings/_reminder_list.html.erb
<% user.default_reminders.each do |reminder| %>
	<tr data-exponent="<%= reminder.exponent %>" data-multiplier="<%= reminder.multiplier %>">
		<td><i class="icon-bell"></i></td>
		<td><%= reminder.to_s %></td>
	</tr>
<% end %>

Remind.me-master/app/views/settings/edit.html.erb
<% if flash[:error] %>
  <div class="alert alert-danger" role="alert"><%= flash[:error] %></div>
<% end %>

<div class="row">
<h2>Uppdatera information för: <%= current_user.name %> </h2>

<%= form_tag settings_path, :method => :put, :class => "form-horizontal span8" do %>
  <input type="hidden" name="_method" value="PUT" />
              <div class="control-group">
                <div class="control-label">
                  <label for="xlInput">Namn</label>
                </div>
                <div class="controls">
                  <%= text_field :user, :name, {:class => "span8", :placeholder => "Namn"} %>
                </div>
              </div>  
              <div class="control-group">
                <div class="control-label">
                  <label for="xlInput">Email</label>
                </div>
                <div class="controls">
                  <%= text_field :user, :email, {:class => "span8", :placeholder => "Email"} %>
                </div>
              </div>
              <div class="control-group">
                <div class="control-label">
                  <label for="xlInput">Telefon</label>
                </div>
                <div class="controls">
                  <%= text_field :user, :phone, {:class => "span8", :placeholder => "Mobilnr"} %>
                </div>
              </div>
              <div class="control-group">
                <div class="controls">
                  <input type="submit" class="btn btn-success save" value="Spara" />
                </div>
              </div>
              <% end %>

          </div>

Remind.me-master/app/views/settings/show.html.erb
<% if flash[:error] %>
	<div class="alert alert-danger" role="alert"><%= flash[:error] %></div>
<% end %>
  <% unless notice.nil? %>
    <div class="alert fade in">
      <button type="button" class="close" data-dismiss="alert">×</button> 
      <%= notice %> 
    </div>
  <% end %>

<h2>Inställningar för: <%= current_user.name %> </h2>

<div id="user-details-section" class="well">
	Epost:  <b><%= current_user.email %> </b> <br />
	Telefonnummer: <b><%= current_user.phone %></b> <br />
  <hr>
  <a href="<%= edit_settings_path %>">Ändra information</a>
</div>


<% if current_user.has_role?(:user) %>
<div id="support-persons-section>">
	<h4>Kalender tillgång</h4>
	<p> Du kan ge andra tillgång till din kalender, skriv in deras epost för att bjuda in dem</p>
	<%= form_tag(invite_user_settings_path(), :class => 'form-inline') do -%>
    <input type="text" placeholder="Epost address" name="email">
    <button type="submit" class="btn btn-primary">Bjud in</button>
	<% end -%>

	<h4>Har tillgång till din kalender:</h4>
	<div class="row">
		<div class="span4">
			<table class="table table-striped .table-bordered "> 
				<thead> 
					<tr> 
						<th>Email</th>  
						<th>Ta bort</th>  
					</tr> 
				</thead> 
				<tbody> 
				<% if @users_with_access_to_user.nil? || @users_with_access_to_user.empty? %>
					<tr> 
						<td>Inga inbjudna</td> 
						<td>-</td>
					</tr> 	
				<% end %>
				<% @users_with_access_to_user.each do |user| -%>
					<tr> 
						<td><%= user.email %></td> 
						<td><%= link_to "x",   remove_user_access_settings_path(:user_id => user)  %></td>
					</tr>
				<% end %>
				</tbody> 
			</table>
		</div>
	</div><!-- Closes row -->
</div><!-- Closes #support-persons-section -->


<div id="default-reminder-section">
	<h4>Påminnelser</h4>
	<div class="row">
		<div class="span6">
			<p>
				Du kan sätta standardpåminnelser som automatiskt sätts på nya händelser. 
				Du kan när som helst ändra dina inställningar för påminnelser.
			</p>
		</div>
		<div class="span4">
			<a href="#reminder-edit-modal" class="btn btn-primary edit-reminders">Ändra påminnelser</a>
		</div>
	</div>
	<div class="row">
		<div class="span6">
			<h5>Dina påminnelser</h5>
			<table class="table default-reminder-list">
				<tbody>
					<%= render :partial => 'reminder_list', :locals => {:user => current_user} %>
				</tbody>
			</table>
		</div>
	</div>
</div>

<div id="reminder-edit-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Editera påminnelser</h3>
  </div>
  <div class="modal-body">
    <p>Här kan du ändra dina standardpåminnelser. Ändringarna börjar gälla så fort du trycker på spara.</p>
    <div style="width:300px;margin:20px auto;">
    	<table class="table reminder-edit-table">
    	</table>
    </div>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Avbryt</button>
    <button class="btn save-reminders-btn btn-primary">Spara</button>
  </div>
</div>



<script type="text/html" id="reminder-edit-row">
    		<tr class="reminder-edit-row">
    			<td style="width:155px">
	    			<input type="text" maxlength="2" class="input-mini reminder-time-input" />
  	  			<select class="reminder-input-select">
    					<option value="m">minuter innan</option>
    					<option value="h">timmar innan</option>
    					<option value="d">dagar innan</option>
    				</select>
    			</td>
    			<td>
    				<div class="pull-right btn-group edit-btn-row">
    					<button type="button" class="btn-mini btn remove-reminder"><i class="icon-remove"></i></button>
    					<button type="button" class="btn-mini btn add-reminder"><i class="icon-plus"></i></button>
    				</div>
    			</td>
    		</tr>
</script>

<script type="text/html" id="reminder-placeholder-row-tmpl">
	<tr class="placeholder-row">
  	<td>
  		Inga påminnelser är tillagda än.
  		<br /><br />
  		<center>
	  		<a href="#" class="btn btn-small add-reminder"><i class="icon-plus"></i> Lägg till</a>
  		</center>
  	</td>
  </tr>
</script>

<script type="text/html" id="reminder-placeholder-row-tmpl">
	<tr class="placeholder-row">
  	<td>
  		<center>
	  		<a href="#" class="btn btn-small add-reminder"><i class="icon-plus"></i> Lägg till</a>
  		</center>
  	</td>
  </tr>
</script>

<script type="text/html" id="reminder-row-section">
<tbody>
{{#reminders}}
<tr class="reminder-edit-row">
	<td style="width:155px">
		<input type="text" maxlength="2" value="{{exponent}}" class="input-mini reminder-time-input" />
		<select class="reminder-input-select">
		  <option value="m" {{#is_minute}}selected{{/is_minute}} >minuter innan</option>
		  <option value="h" {{#is_hour}}selected{{/is_hour}} >timmar innnan</option>
	  	<option value="d" {{#is_day}}selected{{/is_day}} >dagar innnan</option>
		</select>
	</td>
	<td>
		<div class="pull-right btn-group edit-btn-row">
			<button type="button" class="btn-mini btn remove-reminder"><i class="icon-remove"></i></button>
			<button type="button" class="btn-mini btn add-reminder"><i class="icon-plus"></i></button>
		</div>
	</td>
</tr>
{{/reminders}}
{{#no_reminders}}
	<tr class="placeholder-row">
  	<td>
  		<center>
	  		<a href="#" class="btn btn-small add-reminder"><i class="icon-plus"></i> Lägg till</a>
  		</center>
  	</td>
  </tr>
{{/no_reminders}}
</tbody>
</script>
<% end %>

<% content_for :script_files do %>
	<%= javascript_include_tag 'settings' %>
<% end %>