Remind.me-master/config/routes.rb
RemindmeV2::Application.routes.draw do
  # Google OAuth
#  mount GoogleAuthentication, :at => '/auth/google'

  devise_for :users

  devise_scope :user do
    get "logout", :to => "devise/sessions#destroy"
  end

  resource :public, :only => :index
  get '/search' => "application#search"


  namespace 'admin' do 
    resources :terapeuts do 
      member do 
        get :remove
      end
    end
  end

  resource :calendar, :only => [:show, :create, :destroy], controller: 'calendars',  as: 'my_calendar' do
    collection do 
      get :events
      get :persons
    end
  end

  resources :calendars, :only => [:show, :create, :destroy] do
    member do 
      get :events 
      post :create
    end
  end

  resource :statistics do
    get '/people/:people(/from/:from(/to/:to))' => "statistics#show"
  end


  resource :dashboard, :only => :show

  resource :exports do 
    get :perform
  end

  resource :settings do 
    collection do 
      get :refresh_google_status
      post :invite_user
      get :remove_user_access
      post :reminders
    end
  end

  resources :patients do 
    collection do 
      get :autocomplete
    end
    member do
      get :activate
      post :activate
      get :session
      get :notes
      get :delete
      get :resend_invitation
    end
  end
  
  match 'smsteknik/webhook' => 'api/v1/sms#receive_sms', :as => :smsteknik, :via => :post

  namespace 'api' do 
    namespace 'v1' do 
      resource :sms, :only => [] do 
        post :status
      end
    end
  end

  root :to => 'public#index'

end

Remind.me-master/app/views/invitations/access_notification.html.erb
<p>Hej <%= @resource.user_identifier %>!</p>

<p>Du har blivit tillagd och får nu läsa <%= @form.user_identifier %>'s kalender. Logga in och använd kalendern på <%= link_to 'Remindme', root_path(:only_path => false, :host => configatron.app.url) %> </p>

<p>Om du inte vill ha tillgång till den kalendern så ignorera bara det här mailet.</p>

Remind.me-master/app/views/invitations/access_notification.text.erb
Hej <%= @resource.user_identifier %>!
Du har blivit tillagd och får nu läsa <%= @form.user_identifier %>'s kalender. Logga in och använd kalendern på: <%= link_to 'Remindme', root_path(:only_path => false,:host => configatron.app.url) %>


Om du inte vill ha tillgång till den kalendern så ignorera bara det här mailet.

Remind.me-master/app/views/invitations/confirmation_instructions.html.erb
<p>Welcome <%= @resource.email %>!</p>

<p>You can confirm your account email through the link below:</p>

<p><%= link_to 'Confirm my account', confirmation_url(@resource, :confirmation_token => @resource.confirmation_token,:host => configatron.app.url) %></p>

Remind.me-master/app/views/invitations/invitation_instructions.html.erb
<p>Hej <%= @resource.email %>!</p>

<p>Du har blivit inbjuden till RemindMe,  klicka på länken nedan för att acceptera inbjudningen. </p>

<p><%= link_to 'Accept invitation', accept_user_invitation_url(@resource, :invitation_token => @resource.invitation_token,:host => configatron.app.url) %></p>

<p>Om du inte vill ha den här inbjudan så ignorera bara det här mailet.</p>

Remind.me-master/app/views/invitations/invitation_instructions.text.erb
Hej <%= @resource.email %>!

Du har blivit inbjuden till RemindMe,  klicka på länken nedan för att acceptera inbjudningen. 

<%= link_to 'Acceptera inbjudan', accept_user_invitation_url(@resource, :invitation_token => @resource.invitation_token,:host => configatron.app.url) %>

Om du inte vill ha den här inbjudan så ignorera bara det här mailet.

Remind.me-master/app/views/invitations/removed_access_notification.html.erb
<p>Hej <%= @resource.user_identifier %>!</p>

<p>Du har blivit borttagen och får inte längre läsa <%= @form.user_identifier %>'s kalender. </p>

Remind.me-master/app/views/invitations/removed_access_notification.text.erb
Hej <%= @resource.user_identifier %>!

Du har blivit borttagen och får inte längre läsa <%= @form.user_identifier %>'s kalender.

Remind.me-master/app/views/invitations/reset_password_instructions.html.erb
<p>Hej <%= @resource.user_identifier %>!</p>

<p>Någon har begärt en länk för att uppdatera ditt lösenord. </p>

<p><%= link_to 'Ändra ditt lösenord', edit_password_url(@resource, :reset_password_token => @resource.reset_password_token,:host => configatron.app.url) %></p>

<p>Om det inte var du som begärde ändringen så ignorera bara det här epostet.</p>
<p>Ditt lösenord ändras inte förän du klickar på länken ovan och väljer ett nytt lösenord</p>

Remind.me-master/app/views/invitations/terapeut_invitation.html.erb
<p>Hej <%= @resource.user_identifier %>!</p>

<p>Du har blivit inbjuden till RemindMe att jobba som stödperson,  klicka på länken nedan för att acceptera inbjudningen. </p>

<p><%= link_to 'Acceptera inbjudan', accept_user_invitation_url(@resource, :invitation_token => @resource.raw_invitation_token, :only_path => false,:host => configatron.app.url) %></p>

<p>Om du inte vill ha den här inbjudan så ignorera bara det här mailet.</p>

Remind.me-master/app/views/invitations/terapeut_invitation.text.erb
Hej <%= @resource.user_identifier %>!

Du har blivit inbjuden till RemindMe att jobba som stödperson,  klicka på länken nedan för att acceptera inbjudningen.

<%= link_to 'Acceptera inbjudan', accept_user_invitation_url(@resource, :invitation_token => @resource.raw_invitation_token

Om du inte vill ha den här inbjudan så ignorera bara det här mailet.

Remind.me-master/app/views/invitations/unlock_instructions.html.erb
<p>Hello <%= @resource.email %>!</p>

<p>Your account has been locked due to an excessive amount of unsuccessful sign in attempts.</p>

<p>Click the link below to unlock your account:</p>

<p><%= link_to 'Unlock my account', unlock_url(@resource, :unlock_token => @resource.unlock_token,:host => configatron.app.url) %></p>

Remind.me-master/app/views/invitations/user_invitation.html.erb
<p>Hej <%= @resource.user_identifier %>!</p>

<p>Du har blivit inbjuden att använda RemindMe av <%= @resource.terapeut.user_identifier %>.  Klicka på länken nedan för att acceptera inbjudningen. </p>

<p><%= link_to 'Acceptera inbjudan', accept_user_invitation_url(@resource, :invitation_token => @resource.raw_invitation_token, :only_path => false,:host => configatron.app.url) %></p>

<p>Om du inte vill ha den här inbjudan så ignorera bara det här mailet.</p>

Remind.me-master/app/views/invitations/user_invitation.text.erb
Hej <%= @resource.user_identifier %>!


Du har blivit inbjuden att använda RemindMe av <%= @resource.terapeut.user_identifier%>.  Klicka på länken nedan för att acceptera inbjudningen. 

<%= link_to 'Acceptera inbjudan', accept_user_invitation_url(@resource, :invitation_token => @resource.raw_invitation_token, :only_path => false,:host => configatron.app.url) %>

Om du inte vill ha den här inbjudan så ignorera bara det här mailet.

Remind.me-master/app/views/invitations/viewer_invitation.html.erb
<p>Hej <%= @resource.user_identifier %>!</p>

<p>Du har blivit inbjuden till RemindMe att läsa en någons kalender,  klicka på länken nedan för att acceptera inbjudningen. </p>

<p><%= link_to 'Acceptera inbjudan', accept_user_invitation_url(@resource, :invitation_token => @resource.raw_invitation_token, :only_path => false,:host => configatron.app.url) %></p>

<p>Om du inte vill ha den här inbjudan så ignorera bara det här mailet.</p>