Remind.me-master/config/routes.rb
RemindmeV2::Application.routes.draw do
  # Google OAuth
#  mount GoogleAuthentication, :at => '/auth/google'

  devise_for :users

  devise_scope :user do
    get "logout", :to => "devise/sessions#destroy"
  end

  resource :public, :only => :index
  get '/search' => "application#search"


  namespace 'admin' do 
    resources :terapeuts do 
      member do 
        get :remove
      end
    end
  end

  resource :calendar, :only => [:show, :create, :destroy], controller: 'calendars',  as: 'my_calendar' do
    collection do 
      get :events
      get :persons
    end
  end

  resources :calendars, :only => [:show, :create, :destroy] do
    member do 
      get :events 
      post :create
    end
  end

  resource :statistics do
    get '/people/:people(/from/:from(/to/:to))' => "statistics#show"
  end


  resource :dashboard, :only => :show

  resource :exports do 
    get :perform
  end

  resource :settings do 
    collection do 
      get :refresh_google_status
      post :invite_user
      get :remove_user_access
      post :reminders
    end
  end

  resources :patients do 
    collection do 
      get :autocomplete
    end
    member do
      get :activate
      post :activate
      get :session
      get :notes
      get :delete
      get :resend_invitation
    end
  end
  
  match 'smsteknik/webhook' => 'api/v1/sms#receive_sms', :as => :smsteknik, :via => :post

  namespace 'api' do 
    namespace 'v1' do 
      resource :sms, :only => [] do 
        post :status
      end
    end
  end

  root :to => 'public#index'

end

Remind.me-master/app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
	before_filter :authenticate_user!

end

Remind.me-master/app/helpers/dashboards_helper.rb
module DashboardsHelper
end

Remind.me-master/app/views/dashboards/show.html.erb
 <div class="row">
  <div class="span11">
    <h2>Mina sidor</h2>

    <% if current_user.has_role?(:user) %>
    	     <p>
    	     	Välkomment till din sida i Remindme. Välj önskad tjänst nedan
    	     </p>

    <% end %>

	 <% if current_user.has_role?(:terapeut) %>

	     <p>
				Mina sidor är en personlig tjänst för dig som är stödperson. När du loggar in på RemindMe kommer du till Mina sidor. Som stödperson har du behörighet att registrera nya användare. Detta gör du genom att klicka på knappen Skapa användare. Som stödperson kan du själv eller tillsammans med användaren lägga in, redigera och följa upp händelser och påminnelser. 				
			</p>


	<% elsif current_user.has_role?(:admin) %>
			<p>Du är administratör och kan därför lägga till nya terapeuter. Använd försiktigt. 
			</p>
	<% end %>	

	



   </div>
   <div class="row" style="padding-left:45px;">

		<% if current_user.has_role?(:user)   %>

   	   <a href="<%= my_calendar_path() %>" class="span2" style="text-align: center; color: #623B96; border: 2px solid #623B96; border-radius: 15px; margin: 10px 30px 50px 0px;; padding: 10px">
	      <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="120px" height="120px" viewBox="0 0 88 100" enable-background="new 0 0 88 100" space="preserve" style="fill: #623B96"> <path d="M0,32v59.906C0,96.377,3.582,100,8,100h72c4.418,0,8-3.623,8-8.094V32H0z M22,94H6V78h16V94z M22,74H6V58h16V74z M22,54H6 V38h16V54z M42,94H26V78h16V94z M42,74H26V58h16V74z M42,54H26V38h16V54z M62,94H46V78h16V94z M62,74H46V58h16V74z M62,54H46V38h16 V54z M82,94H66V78h16V94z M82,74H66V58h16V74z M82,54H66V38h16V54z"></path> <path d="M80,12H67V3c0-1.657-1.344-3-3-3c-1.657,0-3,1.343-3,3v9H27V3c0-1.657-1.344-3-3-3c-1.657,0-3,1.343-3,3v9H8 c-4.418,0-8,3.623-8,8.093V27v0v1h88v-1v0v-6.907C88,15.623,84.418,12,80,12z M24,26c-3.313,0-6-2.687-6-6 c0-2.219,1.209-4.152,3-5.19V20c0,1.657,1.343,3,3,3c1.656,0,3-1.343,3-3v-5.191c1.792,1.038,3,2.972,3,5.191 C30,23.313,27.314,26,24,26z M64,26c-3.313,0-6-2.687-6-6c0-2.219,1.209-4.152,3-5.19V20c0,1.657,1.343,3,3,3c1.656,0,3-1.343,3-3 v-5.191c1.792,1.038,3,2.972,3,5.191C70,23.313,67.314,26,64,26z"></path> </svg>
	      <h4 > kalender</h4>
	    </a>
	    <% end %>
		<% if current_user.has_role?(:user)  %>

	   	   <a href="<%= statistics_path() %>" class="span2" style="text-align: center; color: #623B96; border: 2px solid #623B96; border-radius: 15px; margin: 10px 30px 50px 0px;; padding: 10px">

	           <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="120px" height="120px" viewBox="0 0 94.798 100" enable-background="new 0 0 94.798 100" space="preserve" style="fill: #623B96"> <path fill="#623B96" d="M78.323,94.936c0,2.802,2.276,5.062,5.068,5.062h6.339c2.798,0,5.068-2.262,5.068-5.062v-50.73 c0-2.799-2.271-5.062-5.068-5.062h-6.339c-2.792,0-5.068,2.263-5.068,5.062V94.936z"></path> <path fill="##623B96" d="M53.805,74.271v20.665c0,2.801,2.275,5.062,5.084,5.062h6.324c2.791,0,5.066-2.263,5.066-5.062V74.271 c0-2.801-2.275-5.076-5.066-5.076h-6.324C56.083,69.194,53.805,71.472,53.805,74.271z"></path> <path fill="#623B96" d="M29.295,81.883v13.055c0,2.801,2.263,5.062,5.069,5.062h6.33c2.792,0,5.069-2.262,5.069-5.062V81.883 c0-2.799-2.277-5.09-5.069-5.09h-6.33C31.559,76.793,29.295,79.084,29.295,81.883z"></path> <path fill="#623B96" d="M34.131,0C15.271,0,0,15.287,0,34.141c0,18.868,15.271,34.153,34.131,34.153 c18.869,0,34.154-15.285,34.154-34.153C68.288,15.287,53,0,34.131,0z M34.134,59.669c-14.097,0-25.51-11.424-25.51-25.526 c0-14.092,11.414-25.518,25.51-25.518v25.576l20.764,14.797C50.267,55.46,42.694,59.669,34.134,59.669z"></path> </svg>
	           	      <h4> statistik</h4>

			</a>
		<% end %>

		<% if current_user.has_role?(:terapeut) %>
   	   <a href="<%= patients_path() %>" class="span2" style="text-align: center; color: #623B96; border: 2px solid #623B96; border-radius: 15px; margin: 10px 30px 50px 0px;; padding: 10px">

		<svg xmlns="http://www.w3.org/2000/svg" xlink="http://www.w3.org/1999/xlink" version="1.1" x="0px" y="0px" width="120px" height="120px" viewBox="0 0 100 100" enable-background="new 0 0 100 100" space="preserve"> <g id="Captions"> </g> <g id="Your_Icon"> <g> <g id="XMLID_2_"> <g> <g id="XMLID_3_"> <g> <path fill="#623B96" d="M42.966,51.018h0.606c-0.168-0.14-0.33-0.268-0.476-0.422c-4.806-4.341-8.473-12.778-8.473-19.599 c0-9.65,7.9-15.998,15.371-15.998c7.465,0,14.968,6.867,14.968,16.513c0,6.818-4.056,14.999-9.074,19.191 c1.031,3.933,6.678,5.22,18.324,8.414c12.939,3.552,11.579,15.705,10.673,18.245c-1.497,4.195-68.574,4.971-69.839,0 c-0.281-2.057-3.246-14.693,9.695-18.245C36.067,56.008,41.709,54.703,42.966,51.018z"></path> <path fill="#623B96" d="M43.572,51.018h-0.606c0.05-0.14,0.088-0.275,0.129-0.422C43.24,50.75,43.405,50.879,43.572,51.018z"></path> </g> </g> </g> </g> <path fill="#623B96" d="M24.331,57.623l2.164-0.592c4.106-1.121,7.357-2.015,9.796-2.903c-1.913-0.847-3.007-1.78-3.362-3.132 c1.643-1.373,3.129-3.331,4.302-5.512c-2.513-4.452-4.157-9.818-4.157-14.486c0-1.709,0.289-3.44,0.814-5.118 c-1.656-1.024-3.512-1.602-5.369-1.602c-5.591,0-11.503,4.75-11.503,11.972c0,5.104,2.744,11.418,6.34,14.667 c0.109,0.115,0.231,0.211,0.356,0.316h-0.454c-0.94,2.758-5.162,3.734-13.638,6.061c-9.684,2.658-7.465,12.114-7.255,13.653 c0.272,1.069,4.622,1.781,10.697,2.181C12.811,63.074,18.851,59.126,24.331,57.623z"></path> <path fill="#623B96" d="M75.385,57.623l-2.164-0.592c-4.106-1.121-7.357-2.015-9.796-2.903c1.913-0.847,3.007-1.78,3.362-3.132 c-1.643-1.373-3.129-3.331-4.302-5.512c2.513-4.452,4.157-9.818,4.157-14.486c0-1.709-0.289-3.44-0.814-5.118 c1.656-1.024,3.512-1.602,5.369-1.602c5.591,0,11.503,4.75,11.503,11.972c0,5.104-2.744,11.418-6.34,14.667 c-0.109,0.115-0.231,0.211-0.356,0.316h0.454c0.94,2.758,5.162,3.734,13.638,6.061c9.684,2.658,7.465,12.114,7.255,13.653 c-0.272,1.069-4.622,1.781-10.697,2.181C86.905,63.074,80.864,59.126,75.385,57.623z"></path> </g> </g> </svg>

        <h4> Dina personer </h4>

       </a>
      <% end %>
      <% if current_user.has_role?(:terapeut) %>
   	   <a href="<%= new_patient_path() %>" class="span2" style="text-align: center; color: #623B96; border: 2px solid #623B96; border-radius: 15px; margin: 10px 30px 50px 0px;; padding: 10px">


      <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" x="0px" y="0px" width="120px" height="120px" viewBox="0 0 100 100" enable-background="new 0 0 100 100" xml:space="preserve" style="fill: #623B96">

		<g id="Layer_6">
			<g>
				<path d="M98.34,78.859c0,0-1.565-4.886-9.782-8.213c-8.217-3.326-17.322-7.04-17.322-7.04S71,57.348,68,57.348V51.87    c0,0,0.301-1.566,1.084-2.544c0.781-0.978,2.204-4.5,2.596-7.239c0,0,1.004-0.783,1.396-2.543c0.392-1.761,1.97-7.043-0.771-6.261    c0,0,1.669-12.091-0.679-15.808C69.278,13.758,63.319,9,59.016,9h-2.894c-4.304,0-10.271,4.758-12.618,8.475    c-2.347,3.717-0.686,15.705-0.686,15.705c-2.739-0.782-1.174,4.552-0.783,6.313c0.392,1.76,1.37,2.569,1.37,2.569    c0.391,2.739,1.798,6.274,2.58,7.251C46.768,50.291,47,51.87,47,51.87v5.478c-3,0-3.167,6.261-3.167,6.261    s-9.103,3.717-17.319,7.043C25.218,71.176,24,71.739,23,72.316V73h11v7c23,0,61.684,0,62.948,0    C98.72,80,98.34,78.859,98.34,78.859z"></path>
				<polygon points="21,64 13,64 13,75 2,75 2,83 13,83 13,94 21,94 21,83 32,83 32,75 21,75   "></polygon>
			</g>
		</g>
		</svg>
  	<h4> Lägg till person</h4>

       </a>
      <% end %>



		<% if current_user.has_role?(:admin) %>
   	   <a href="<%= admin_terapeuts_path() %>" class="span2" style="text-align: center; color: #623B96; border: 2px solid #623B96; border-radius: 15px; margin: 10px 30px 50px 0px;; padding: 10px">

		<svg xmlns="http://www.w3.org/2000/svg" xlink="http://www.w3.org/1999/xlink" version="1.1" x="0px" y="0px" width="120px" height="120px" viewBox="0 0 100 100" enable-background="new 0 0 100 100" space="preserve"> <g id="Captions"> </g> <g id="Icon"> <g> <g id="XMLID_2_"> <g> <g id="XMLID_3_"> <g> <path fill="#623B96" d="M42.966,51.018h0.606c-0.168-0.14-0.33-0.268-0.476-0.422c-4.806-4.341-8.473-12.778-8.473-19.599 c0-9.65,7.9-15.998,15.371-15.998c7.465,0,14.968,6.867,14.968,16.513c0,6.818-4.056,14.999-9.074,19.191 c1.031,3.933,6.678,5.22,18.324,8.414c12.939,3.552,11.579,15.705,10.673,18.245c-1.497,4.195-68.574,4.971-69.839,0 c-0.281-2.057-3.246-14.693,9.695-18.245C36.067,56.008,41.709,54.703,42.966,51.018z"></path> <path fill="#623B96" d="M43.572,51.018h-0.606c0.05-0.14,0.088-0.275,0.129-0.422C43.24,50.75,43.405,50.879,43.572,51.018z"></path> </g> </g> </g> </g> <path fill="#623B96" d="M24.331,57.623l2.164-0.592c4.106-1.121,7.357-2.015,9.796-2.903c-1.913-0.847-3.007-1.78-3.362-3.132 c1.643-1.373,3.129-3.331,4.302-5.512c-2.513-4.452-4.157-9.818-4.157-14.486c0-1.709,0.289-3.44,0.814-5.118 c-1.656-1.024-3.512-1.602-5.369-1.602c-5.591,0-11.503,4.75-11.503,11.972c0,5.104,2.744,11.418,6.34,14.667 c0.109,0.115,0.231,0.211,0.356,0.316h-0.454c-0.94,2.758-5.162,3.734-13.638,6.061c-9.684,2.658-7.465,12.114-7.255,13.653 c0.272,1.069,4.622,1.781,10.697,2.181C12.811,63.074,18.851,59.126,24.331,57.623z"></path> <path fill="#623B96" d="M75.385,57.623l-2.164-0.592c-4.106-1.121-7.357-2.015-9.796-2.903c1.913-0.847,3.007-1.78,3.362-3.132 c-1.643-1.373-3.129-3.331-4.302-5.512c2.513-4.452,4.157-9.818,4.157-14.486c0-1.709-0.289-3.44-0.814-5.118 c1.656-1.024,3.512-1.602,5.369-1.602c5.591,0,11.503,4.75,11.503,11.972c0,5.104-2.744,11.418-6.34,14.667 c-0.109,0.115-0.231,0.211-0.356,0.316h0.454c0.94,2.758,5.162,3.734,13.638,6.061c9.684,2.658,7.465,12.114,7.255,13.653 c-0.272,1.069-4.622,1.781-10.697,2.181C86.905,63.074,80.864,59.126,75.385,57.623z"></path> </g> </g> </svg>

        <h4> Hantera terapeuter</h4>

       </a>
      <% end %>


		<% if current_user.has_role?(:user) %>
   	   <a href="<%= settings_path() %>" class="span2" style="text-align: center; color: #623B96; border: 2px solid #623B96; border-radius: 15px; margin: 10px 30px 50px 0px;; padding: 10px">
      <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Layer_1" x="0px" y="0px" width="120px" height="120px" viewBox="0 0 100 100" enable-background="new 0 0 100 100" xml:space="preserve" style="fill: #623B96">
		<g>
			<path d="M99,57.669V41.331L87.822,38.01c-0.738-2.41-1.605-4.72-2.77-6.908l5.741-10.392L79.266,9.158l-10.38,5.693   c-2.188-1.164-4.492-1.936-6.901-2.673L58.669,1H42.331L39.01,12.178c-2.41,0.737-4.72,1.605-6.908,2.769L21.71,9.206   L10.158,20.734l5.693,10.379c-1.164,2.188-2.436,4.493-3.173,6.902L1,41.331v16.338l11.678,3.321   c0.737,2.41,1.855,4.721,3.019,6.908l-5.616,10.391l11.591,11.553l10.411-5.693c2.188,1.164,4.508,2.437,6.917,3.174L42.331,99   h16.338l3.321-11.678c2.41-0.737,4.721-1.855,6.908-3.02l10.391,5.616l11.553-11.591l-5.693-10.41   c1.164-2.188,1.937-4.509,2.674-6.918L99,57.669z M50.5,79.873c-16.774,0-30.373-13.599-30.373-30.373   c0-16.774,13.598-30.372,30.373-30.372c16.775,0,30.373,13.598,30.373,30.372C80.873,66.274,67.275,79.873,50.5,79.873z"></path>
			<path d="M50,46.996c-3.133,0-6,1.997-6,4.459v13.5c0,2.463,2.867,4.459,6,4.459s6-1.996,6-4.459v-13.5   C56,48.993,53.133,46.996,50,46.996z"></path>
			<path d="M50,29.586c-3.133,0-6,1.996-6,4.459v3.176c0,2.462,2.867,4.458,6,4.458s6-1.996,6-4.458v-3.176   C56,31.583,53.133,29.586,50,29.586z"></path>
		</g>
	 </svg>
     <h4> Inställningar </h4>

       </a>
      <% end %>


   </div>

	<% if current_user.has_role?(:viewer) %>
    <div class="span11 well" >
	    <h4>Användare vars kalender du har tillgång till:</h4>
		<table class="zebra-striped span5" >
			<% current_user.permission_to.each do |user| %>
			<tr>
				<td><%= user.email %></td>
				<td><a href="<%= calendar_path(user.id)   %>">Gå till Kalender</a></td>
			</tr>
			<% end %>
		</table>
  </div>
  <% end %>
 </div>	