Remind.me-master/config/routes.rb
RemindmeV2::Application.routes.draw do
  # Google OAuth
#  mount GoogleAuthentication, :at => '/auth/google'

  devise_for :users

  devise_scope :user do
    get "logout", :to => "devise/sessions#destroy"
  end

  resource :public, :only => :index
  get '/search' => "application#search"


  namespace 'admin' do 
    resources :terapeuts do 
      member do 
        get :remove
      end
    end
  end

  resource :calendar, :only => [:show, :create, :destroy], controller: 'calendars',  as: 'my_calendar' do
    collection do 
      get :events
      get :persons
    end
  end

  resources :calendars, :only => [:show, :create, :destroy] do
    member do 
      get :events 
      post :create
    end
  end

  resource :statistics do
    get '/people/:people(/from/:from(/to/:to))' => "statistics#show"
  end


  resource :dashboard, :only => :show

  resource :exports do 
    get :perform
  end

  resource :settings do 
    collection do 
      get :refresh_google_status
      post :invite_user
      get :remove_user_access
      post :reminders
    end
  end

  resources :patients do 
    collection do 
      get :autocomplete
    end
    member do
      get :activate
      post :activate
      get :session
      get :notes
      get :delete
      get :resend_invitation
    end
  end
  
  match 'smsteknik/webhook' => 'api/v1/sms#receive_sms', :as => :smsteknik, :via => :post

  namespace 'api' do 
    namespace 'v1' do 
      resource :sms, :only => [] do 
        post :status
      end
    end
  end

  root :to => 'public#index'

end

Remind.me-master/app/controllers/patients_controller.rb
#coding:utf-8
class PatientsController < ApplicationController

	# This is incompleate and need to bee adapted to the new user structure

	before_filter :admin_or_terapeut_required

	def index
		@patients = current_user.patients.order("last_name").paginate(:per_page => 25, :page => params[:page])
	end
	
	def new
		@patient = User.new
	end
	
	def show
		@patient = current_user.patients.find(params[:id])		
	end
	
	def edit
		@patient = current_user.patients.find(params[:id])
	end
	
	def create

		@patient = current_user.patients.invite!({:email => params[:patient][:email], :name => params[:patient][:name], :phone => params[:patient][:phone]}, current_user) do |p|
			p.given_permission_to << current_user 
			p.terapeut = current_user
		end
			

		# @patient = current_user.patients.create(params[:patient])

		if @patient.errors.empty? 
			# redirect_to activate_patient_path(@patient) and return
			redirect_to patients_path and return

		else
			flash[:error] = "Det gick inte att spara, se nedan!"
			render :action => :new and return
		end

	end
	
	def update
		@patient = @current_user.patients.find(params[:id])
		if @patient.update_attributes(params[:patient])
			flash[:notice] 	= "#{@patient.name} har uppdaterats"
			redirect_to edit_patient_path(@patient) and return
		else
			flash[:error] 	= "Det gick inte att spara, se nedan!"
			render :action => :edit and return
		end
	end

	def resend_invitation
		begin
			u = User.find(params[:id])
			u.invite!() 
			flash[:notice] = "Ny inbjudan skickad"
			redirect_to :back

		rescue ActiveRecord::RecordNotFound
			redirect_to :back
		end
	end

	def delete
		@patient = User.find(params[:id])		
		if can?(:destroy, @patient) && @patient.destroy
			flash[:notice] = "Användare borttagen."
		else
			flash[:error] = "Du har inte möjlighet att genomföra detta."
		end
		redirect_to patients_path and return 
	end


	# Den här vet jag inte hur den är konstruerad, DS?
	def autocomplete
	  tags = current_user.owned_tags.where(["name like ?", '%'+params[:term]+'%'])
		render :text => tags.map{|t| t.name}.to_json, :status => 200 and return
	end


end

Remind.me-master/app/helpers/patients_helper.rb
module PatientsHelper
end

Remind.me-master/app/views/patients/_form.html.erb
  <% if flash[:error] %>
    <p class ="clearfix error"><%= flash[:error] %></p>
  <% end %>

	<div class="clearfix <%= @patient.errors[:name].empty? ? '' : 'error' %>">
    <label for="xlInput">Namn</label>
    <div class="input">
			<%= text_field :patient, :name, {:class => "xlarge", :size => 50} %>
			<% if !@patient.errors[:name].empty? %>
      	<span class="help-inline">Namn får inte vara blankt.</span>    
			<% end %>
    </div>
  </div>
	<div class="clearfix <%= @patient.errors[:email].empty? ? '' : 'error' %>">
    <label for="xlInput">Email</label>
    <div class="input">
			<%= text_field :patient, :email, {:class => "xlarge", :size => 50} %>
			<% if !@patient.errors[:email].empty? %>
        <% if User.find_by_email(@patient.email) %>
          <span class="help-inline">Email måste vara unik </span>
        <% else %>
        	<span class="help-inline">Email måste vara valid, och får inte vara blank.</span>    
        <% end %>
			<% end %>
    </div>
  </div>
	<div class="clearfix <%= @patient.errors[:phone].empty? ? '' : 'error' %>">
    <label for="xlInput">Telefon</label>
    <div class="input">
			<%= text_field :patient, :phone, {:class => "xlarge", :size => 50} %>
			<% if !@patient.errors[:phone].empty? %>
      	<span class="help-inline">Telefonnummer får inte vara blankt.</span>    
			<% else %>				
      	<span class="help-inline">Påminnelser skickas till det här numret!</span>    
			<% end %>
    </div>
	</div>

Remind.me-master/app/views/patients/_reminder_list.html.erb
<% user.default_reminders.each do |reminder| %>
	<tr data-exponent="<%= reminder.exponent %>" data-multiplier="<%= reminder.multiplier %>">
		<td><i class="icon-bell"></i></td>
		<td><%= reminder.to_s %></td>
	</tr>
<% end %>

Remind.me-master/app/views/patients/activate.html.erb
<h1>Aktivera <%= @patient.name %></h1>
<p class="span10">
	Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas faucibus mollis interdum. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
</p>
<br />
<ul class="tabs">
	<li class="active"><a href="#email">Aktivera per email</a></li>
	<li><a href="#immediate">Aktivera omedelbart</a></li>
</ul>


<div class="tab-content">
	
	<div id="immediate" class="tab-pane">
			<%= form_tag activate_patient_path(@patient) do %>
			<fieldset>
				<legend>Aktivera omedelbart</legend>
				<div class="clearfix">
					<label>Lösenord</label>
					<div class="input">
						<%= password_field :activation, :password, {:class => "xxlarge", :size => 50} %>
						<br />
		      	<span class="help-inline">Tänk på att välja ett lösenord du kommer ihåg, men som är svårt att gissa!</span>    
					</div>
				</div>
				<div class="clearfix">
					<label for="subjectfield">Repetera lösenord</label>
					<div class="input">
						<%= password_field :activation, :password_confirmation, {:class => "xxlarge", :size => 50, :id => "subjectfield"} %>
					</div>
				</div>
				<br />
				<div class="actions">
					<input type="submit" class="btn success" value="Spara">
				</div>
			</fieldset>
			<% end %>
	</div>

	<div id="email" class="tab-pane active">
		<%= form_tag activate_patient_path(@patient) do %>
		<fieldset>
			<legend>Aktivera per email</legend>
			<div class="clearfix">
				<label>Email</label>
				<div class="input">
					<%= text_field :patient, :email, {:disabled => true, :class => "xxlarge", :size => 50} %>
				</div>
			</div>
			<div class="clearfix">
				<label for="subjectfield">Ämne</label>
				<div class="input">
					<%= text_field :activation, :subject, {:class => "xxlarge", :size => 50, :id => "subjectfield", :value => "[Remindme.com] Aktivera konto"} %>
				</div>
			</div>
			<div class="clearfix">
				<label for="bodyfield">Body</label>
				<div class="input">
					<textarea name="activation[content]" class="xxlarge" rows="9" id="bodyfield">
Hej <%= @patient.name %>, 

Donec id elit non mi porta gravida at eget metus. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Donec id elit non mi porta gravida at eget metus.

<%= configatron.base.url %>/activate/<%= @patient.invite_hash %>

//Remindme.com	
					</textarea>
					<span class="help-block">
						Du kan ändra allting utom själva länken som börjar med <%= configatron.base.url %>...
					</span>
				</div>
			</div>
			<br />
			<div class="actions">
				<input type="hidden" name="activation[invite_hash]" value="<%= @patient.invite_hash %>" />
				<input type="submit" class="btn success" value="Skicka">
			</div>
		</fieldset>
		<% end %>
	</div>
</div>

<% content_for :script_files do %>
<%= javascript_include_tag '/assets/bootstrap-tabs.js' %>
<% end %>

<% content_for :page_script do  %>
$(document).ready(function(){
	$(".tabs").tabs();
})
<% end %>

Remind.me-master/app/views/patients/edit.html.erb
<h1><%= @patient.name %></h1>
	<ul class="tabs nav nav-tabs">

  <li><a href="<%= patient_path(@patient) %>">Översikt</a></li>
  <li class="active"><a href="<%= edit_patient_path(@patient) %>">Editera</a></li>
<!--  <li><a href="<%= notes_patient_path(@patient) %>">Anteckningar*</a></li> -->
</ul>
<div class="span16">
	<div class="row">
	<% if flash[:error] %>
	<div class="span10 offset3">
			<div class="alert-message error">
        <p><%= flash[:error] %></p>
      </div>
	</div>
	<% end %>
	</div>
	<%= form_tag patient_path(@patient), {:method => :put, :id => "edit-patient-form"} do %>
		<fieldset>
			<legend>Editera <%= @patient.name %></legend>
   		<%= render :partial => 'form' %>
  	</fieldset>
			<br />
		<div class="actions">
      
      <a href="<%= patients_path %>" class="btn">Avbryt</a> &nbsp; <input type="submit" class="btn success" value="Spara">
    </div>
	<% end %>
	<fieldset>
		<legend>Påminnelser</legend>
		<div id="default-reminder-section">
		  <div class="row">
		    <div class="span6">
		      <p>
		        Du kan sätta standardpåminnelser som automatiskt sätts på nya händelser. 
		        Du kan när som helst ändra dina inställningar för påminnelser.
		      </p>
		    </div>
		    <div class="span4">
		      <a href="#reminder-edit-modal" class="btn btn-primary edit-reminders">Ändra påminnelser</a>
		    </div>
		  </div>
		  <div class="row">
		    <div class="span6">
		      <h5>Dina påminnelser</h5>
		      <table class="table default-reminder-list">
		        <tbody>
		          <%= render :partial => 'reminder_list', :locals => {:user => @patient } %>
		        </tbody>
		      </table>
		    </div>
		  </div>
		</div>
	</fieldset>
	<fieldset>
		<legend>Ta bort</legend>
		<p>Var försiktig - du kan inte ångra det här och användaren och samtlig användardata tas bort omedelbart.</p>
		<a class="btn btn-primary btn-danger" onclick="return confirm('Du kan inte ändra dig?')" href="<%= delete_patient_path(@patient) %>">Ta bort patient</a>
	</fieldset>
</div>

<% content_for :page_styles do %>
	<%= stylesheet_link_tag 'tags'%>
<% end %>

<% content_for :script_files do %>
	<%= javascript_include_tag 'tags'%>
	<%= javascript_include_tag 'settings'%>
<% end %>

<% content_for :page_script do %>
	$(document).ready(function(){
		$("#edit-patient-form").submit(function(){
			var tag_val = $("#tag-field_tag").val();
			$("#tag-field").addTag(tag_val);
		});
	});
<% end %>


<div id="reminder-edit-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Editera påminnelser</h3>
  </div>
  <div class="modal-body">
    <p>Här kan du ändra dina standardpåminnelser. Ändringarna börjar gälla så fort du trycker på spara.</p>
    <div style="width:300px;margin:20px auto;">
    	<table class="table reminder-edit-table">
    	</table>
    </div>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Avbryt</button>
    <button class="btn save-reminders-btn btn-primary" data-edit-for="<%= @patient.id %>">Spara</button>
  </div>
</div>



<script type="text/html" id="reminder-edit-row">
    		<tr class="reminder-edit-row">
    			<td style="width:155px">
	    			<input type="text" maxlength="2" class="input-mini reminder-time-input" />
  	  			<select class="reminder-input-select">
    					<option value="m">minuter innan</option>
    					<option value="h">timmar innan</option>
    					<option value="d">dagar innan</option>
    				</select>
    			</td>
    			<td>
    				<div class="pull-right btn-group edit-btn-row">
    					<button type="button" class="btn-mini btn remove-reminder"><i class="icon-remove"></i></button>
    					<button type="button" class="btn-mini btn add-reminder"><i class="icon-plus"></i></button>
    				</div>
    			</td>
    		</tr>
</script>

<script type="text/html" id="reminder-placeholder-row-tmpl">
	<tr class="placeholder-row">
  	<td>
  		Inga påminnelser är tillagda än.
  		<br /><br />
  		<center>
	  		<a href="#" class="btn btn-small add-reminder"><i class="icon-plus"></i> Lägg till</a>
  		</center>
  	</td>
  </tr>
</script>

<script type="text/html" id="reminder-placeholder-row-tmpl">
	<tr class="placeholder-row">
  	<td>
  		<center>
	  		<a href="#" class="btn btn-small add-reminder"><i class="icon-plus"></i> Lägg till</a>
  		</center>
  	</td>
  </tr>
</script>

<script type="text/html" id="reminder-row-section">
<tbody>
{{#reminders}}
<tr class="reminder-edit-row">
	<td style="width:155px">
		<input type="text" maxlength="2" value="{{exponent}}" class="input-mini reminder-time-input" />
		<select class="reminder-input-select">
		  <option value="m" {{#is_minute}}selected{{/is_minute}} >minuter innan</option>
		  <option value="h" {{#is_hour}}selected{{/is_hour}} >timmar innnan</option>
	  	<option value="d" {{#is_day}}selected{{/is_day}} >dagar innnan</option>
		</select>
	</td>
	<td>
		<div class="pull-right btn-group edit-btn-row">
			<button type="button" class="btn-mini btn remove-reminder"><i class="icon-remove"></i></button>
			<button type="button" class="btn-mini btn add-reminder"><i class="icon-plus"></i></button>
		</div>
	</td>
</tr>
{{/reminders}}
{{#no_reminders}}
	<tr class="placeholder-row">
  	<td>
  		<center>
	  		<a href="#" class="btn btn-small add-reminder"><i class="icon-plus"></i> Lägg till</a>
  		</center>
  	</td>
  </tr>
{{/no_reminders}}
</tbody>
</script>

Remind.me-master/app/views/patients/index.html.erb
<% if current_user.has_role?(:terapeut) %>
	<a href="<%= new_patient_path %>" class="btn success">Ny person</a>
<% end %>
<br /><br />
<table class="table table-striped span10	">
	<thead>
		<tr>
			<th>Namn</th>
			<th>Senaste inlogg</th>
			<th>Status</th>
			<th>Val</th>
		</tr>
	</thead>
	<tbody>
		<% @patients.each do |patient| %>
		<tr>
			<td >
				<a href="<%= patient_path(patient) %>">
					<%= patient.name %>
				</a>
			</td>
			<td>
				<% if patient.current_sign_in_at %>
					<%= time_ago_in_words(patient.current_sign_in_at) %> sedan
				<% else %>
					Aldrig
				<% end %>
			</td>
			<td>
				<% if patient.sign_in_count > 0 %>
					Aktiv
				<%  elsif patient.invitation_accepted_at.nil? %>
					Inbjuden
				<%  else %>
					N/A
				<%  end %>
			</td>	
			<td style="text-align: center;">
				<a href="<%= edit_patient_path(patient) %>">Editera</a>&nbsp;|&nbsp;
				<a href="<%= patient_path(patient) %>">Visa</a> 
			</td>	
		</tr>
		<% end %>
	</tbody>
</table>
 <div class="pagination">
    <ul>
			<% if @patients.previous_page %>
				<li class="prev"><a href="<%= patients_path(:page => @patients.previous_page) %>">&larr; Previous</a></li>    	
			<% else %>
    		<li class="prev disabled"><a href="#">&larr; Previous</a></li>
			<% end %>
			<% @patients.total_pages.times do |i| %>
      	<li class="<%= i+1 == @patients.current_page ? 'active' : '' %>"><a href="<%= patients_path(:page => i+1) %>"><%= i+1 %></a></li>
			<% end %>
			<% if @patients.next_page %>
    		<li class="next"><a href="<%= patients_path(:page => @patients.next_page ) %>">Next &rarr;</a></li>			
			<% else %>
      	<li class="next disabled"><a href="#">Next &rarr;</a></li>
			<% end %>
    </ul>
  </div>

Remind.me-master/app/views/patients/new.html.erb
<div class="row">
	<div class="span11">
<h1>Ny Person</h1>
<p>
	När du skapat en person kan du antingen aktivera den på en gång, eller 
	skicka inbjudan till personens email.
</p>
<br />
<%= form_tag patients_path do %>
<fieldset>
	<legend>Information</legend>
 	<%= render :partial => 'form' %>
	<br />
	<div class="actions">
    <a href="<%= patients_path %>" class="btn">Avbryt</a> &nbsp; <input type="submit" class="btn success" value="Spara">
  </div>
</fieldset>
<% end %>

</div>

Remind.me-master/app/views/patients/show.html.erb
<div class="row">
<% if @patient.invitation_accepted_at.nil? %>
	<a href="<%= resend_invitation_patient_path(@patient.id) %>" class="btn" style="float: right;margin:0px 10px 0px 0px">Skicka ny inbjudan</a>

<% else %> 
	<a href="<%=  calendar_path(@patient.id) %>" class="btn" style="float: right;">Kalender</a>
	<a href="/statistics/people/<%= @patient.id %>" class="btn" style="float: right;margin:0px 10px 0px 0px">Statistik</a>
<% end %>
<h1><%= @patient.name %></h1>

<ul class="">

	<ul class="tabs nav nav-tabs">
  <li class="active"><a href="<%= patient_path(@patient) %>">Översikt</a></li>
  <li><a href="<%= edit_patient_path(@patient) %>">Editera</a></li>
<!--  <li><a href="<%= notes_patient_path(@patient) %>">Anteckningar*</a></li> -->
</ul>

<div class="span12">
	<h3>Info</h3>
	<table class="condensed-table span5">
		<tr>
			<td class="span2">Email</td>
			<td class="span3"><%= @patient.email %></td>
		</tr>
		<tr>
			<td class="span2">Telefon</td>
			<td class="span3"><%= @patient.phone %></td>
		</tr>
	</table>
</div>

</div>